// Mocks generated by Mockito 5.4.4 from annotations
// in posts_app/test/features/comments/data/repositories/comments_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:posts_app/core/network/network_info.dart' as _i7;
import 'package:posts_app/features/comments/data/data_sources/comments_local_data_source.dart'
    as _i6;
import 'package:posts_app/features/comments/data/data_sources/comments_remote_data_source.dart'
    as _i3;
import 'package:posts_app/features/comments/data/models/comment_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnit_0 extends _i1.SmartFake implements _i2.Unit {
  _FakeUnit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsRemoteDataSource extends _i1.Mock
    implements _i3.CommentsRemoteDataSource {
  MockCommentsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.CommentModel>> getComments(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValue:
            _i4.Future<List<_i5.CommentModel>>.value(<_i5.CommentModel>[]),
      ) as _i4.Future<List<_i5.CommentModel>>);
}

/// A class which mocks [CommentsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsLocalDataSource extends _i1.Mock
    implements _i6.CommentsLocalDataSource {
  MockCommentsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.CommentModel>> getCachedComments(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedComments,
          [postId],
        ),
        returnValue:
            _i4.Future<List<_i5.CommentModel>>.value(<_i5.CommentModel>[]),
      ) as _i4.Future<List<_i5.CommentModel>>);

  @override
  _i4.Future<_i2.Unit> cacheComments(
    List<_i5.CommentModel>? commentModels,
    int? postId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheComments,
          [
            commentModels,
            postId,
          ],
        ),
        returnValue: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #cacheComments,
            [
              commentModels,
              postId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Unit>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
